version: '3.8'
services:
  vault:
    image: hashicorp/vault:latest
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    command: server -dev  # Запускаем в режиме разработки
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=myroot  # Устанавливаем простой root-токен
      - VAULT_ADDR=http://127.0.0.1:8200